In [102]:
import numpy as np
import scipy.stats as stats
import numpy.ma as ma


a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [11]:
1. np.count_nonzero(a[a < 0])
#There are 4 negative numbers.

4

In [12]:
2. np.count_nonzero(a[a > 0])
#There are 5 positive numbers.

5

In [30]:
mask = [True, True, True, False, False, False, False, False, False, False, False, False]

In [31]:
3. print(a[mask])

[ 4 10 12]


In [32]:
np.count_nonzero(a[mask])
#There are 3 positive even numbers.

3

In [33]:
4. a + 3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [34]:
np.count_nonzero(a[a > 0])

'''There are 5 positive numbers aftera adding 3 to all of the numbers 
in the array.

5

In [ ]:
#If you squared each number, what would the new mean and standard 
#deviation be?

In [104]:
a1 = a ** 2
a1

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [40]:
np.mean(a1)

#The mean would be 74.

74.0

In [8]:
np.std(a1)

#The Standard Deviation would be 144.02

144.0243035046516

In [ ]:
# A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
#Center the data set. See this link for more on centering.

In [9]:
a1 - 74

array([-58,  26,  70, 455, -70, -73, -74, -74, -74, -38, -65, -25])

In [ ]:
#Calculate the z-score for each data point. Recall that the z-score is given by:

In [47]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
# Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [52]:
sum(a)

55

In [ ]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of 
#all the numbers in the above list

In [53]:
min_of_a = min(a)
min_of_a

1

In [ ]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of 
# all the numbers in the above list

In [54]:
max_of_a = max(a)
max_of_a

10

In [ ]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all
# the numbers in the above list

In [56]:
mean_of_a = np.mean(a)
mean_of_a

5.5

In [ ]:
# Exercise 5 - Make a variable named product_of_a to hold the product of 
# multiplying all the numbers in the above list together

In [57]:
product_of_a = np.product(a)
product_of_a

3628800

In [ ]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each 
# number in a squared like [1, 4, 9, 16, 25...]

In [58]:
squares_of_a = [ai**2 for ai in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the 
# odd numbers

In [65]:
mask = [True, False, True, False, True, False, True, False, True, False]

In [67]:
odds_in_a = a[mask]
odds_in_a

array([1, 3, 5, 7, 9])

In [ ]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [68]:
mask = [False, True, False, True, False, True, False, True, False, True]

In [70]:
evens_in_a = a[mask]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [144]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of 
#squares for this list of two lists.
b = [
    [3, 4, 5], 
    [6, 7, 8]
]

In [129]:
b2 = np.array(b)
b2

array([[3, 4, 5],
       [6, 7, 8]])

In [130]:
sum_of_b = sum(b2)
sum_of_b
sum(sum_of_b)

33

In [84]:
min_of_b = min(b)
min_of_b
min(min_of_b)

3

In [86]:
max_of_b = max(b)
max_of_b
max(max_of_b)

8

In [90]:
mean_of_b = np.mean(b)
mean_of_b

5.5

In [92]:
product_of_b = np.product(b)
product_of_b

20160

In [113]:
squares_of_b = b2 ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [146]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [148]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [ ]:
# Exercise 9 - print out the shape of the array b.

In [150]:
np.shape(b2)

(2, 3)

In [ ]:
# Exercise 10 - transpose the array b.

In [151]:
b2.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [ ]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [155]:
Reshape_1 = b2.reshape(1, 6)
Reshape_1

array([[3, 4, 5, 6, 7, 8]])

In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [157]:
Reshape_2 = b2.reshape(6, 1)
Reshape_2

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [171]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

c1 = np.array(c)
c1

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Exercise 2 - Determine the standard deviation of c.

In [163]:
np.std(c1)

2.581988897471611

In [ ]:
# Exercise 3 - Determine the variance of c.

In [167]:
np.var(c1)

6.666666666666667

In [ ]:
# Exercise 4 - Print out the shape of the array c

In [168]:
np.shape(c1)

(3, 3)

In [ ]:
# Exercise 5 - Transpose c and print out transposed result.

In [169]:
c1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# Exercise 6 - Get the dot product of the array c with c. 

In [176]:
np.product(c1)

362880

In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [177]:
sum_of_c = sum(c1)
sum_of_c
sum(sum_of_c)

45

In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [183]:
c1_transposed_prod = np.product(c1.T)
c1_normal_prod = np.product(c1)
c1_transposed_prod*c1_normal_prod

131681894400

In [223]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d1 = np.array(d)

In [190]:
np.std(d)

88.35298523536146

In [ ]:
# Exercise 1 - Find the sine of all the numbers in d

In [191]:
import math as m

In [202]:
np.sin(d1)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [ ]:
# Exercise 2 - Find the cosine of all the numbers in d

In [203]:
np.cos(d1)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d

In [204]:
np.tan(d1)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [ ]:
# Exercise 4 - Find all the negative numbers in d

In [205]:
np.count_nonzero((d1[d1 < 0]))

4

In [ ]:
# Exercise 5 - Find all the positive numbers in d

In [206]:
np.count_nonzero((d1[d1 > 0]))

12

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [228]:
import pandas
d1
pd_vc = pandas.value_counts(d)
pd_vc

[90, 30, 45, 0, 120, 180]      1
[45, -90, -30, 270, 90, 0]     1
[60, 45, -45, 90, -45, 180]    1
dtype: int64

In [219]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [221]:
np.count_nonzero(pd_vc)

3

In [ ]:
# Exercise 8 - Print out the shape of d.

In [226]:
print(np.shape(d1))

(3, 6)


In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

In [227]:
print(np.shape(d1.T))

(6, 3)


In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [230]:
Reshape_d = d1.reshape(9, 2)
Reshape_d

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])