In [46]:
import numpy as np
import scipy.stats as stats

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [11]:
np.count_nonzero(a[a < 0])

4

In [12]:
np.count_nonzero(a[a > 0])

5

In [30]:
mask = [True, True, True, False, False, False, False, False, False, False, False, False]

In [31]:
print(a[mask])

[ 4 10 12]


In [32]:
np.count_nonzero(a[mask])

3

In [33]:
a + 3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [34]:
np.count_nonzero(a[a > 0])

5

In [ ]:
#If you squared each number, what would the new mean and standard 
#deviation be?

In [39]:
a1 = a ** 2

In [40]:
np.mean(a1)

74.0

In [41]:
np.std(a1)

144.0243035046516

In [ ]:
# A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
#Center the data set. See this link for more on centering.

In [42]:
a1 - 74

array([-58,  26,  70, 455, -70, -73, -74, -74, -74, -38, -65, -25])

In [ ]:
#Calculate the z-score for each data point. Recall that the z-score is given by:

In [47]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [ ]:
# Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [48]:
sum(a)

36

In [ ]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of 
#all the numbers in the above list

In [49]:
min_of_a = min(a)

-7

In [ ]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of 
# all the numbers in the above list

In [51]:
max_of_a = max(a)

In [ ]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all
# the numbers in the above list

In [53]:
mean_of_a = np.mean(a)

In [ ]:
# Exercise 5 - Make a variable named product_of_a to hold the product of 
# multiplying all the numbers in the above list together

In [54]:
product_of_a = np.product(a)

In [ ]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each 
# number in a squared like [1, 4, 9, 16, 25...]

In [55]:
squares_of_a = a ** 2

In [ ]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the 
# odd numbers

In [ ]:
odds_in_a = 

In [ ]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.